apiVersion: apps/v1
kind: Deployment
metadata:
  name: sigadash-frontend
  namespace: sigadash
  labels:
    app: sigadash-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sigadash-frontend
  template:
    metadata:
      labels:
        app: sigadash-frontend
    spec:
      containers:
        - name: sigadash-frontend
          image: ECR_IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8080
          env:
            - name: REACT_APP_ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: variables-env
                  key: ENVIRONMENT
                  optional: true
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: variables-env
                  key: API_URL
                  optional: true
            - name: REACT_APP_AMSA_LOGIN_URL
              valueFrom:
                configMapKeyRef:
                  name: variables-env
                  key: AMSA_LOGIN_URL
                  optional: true
            - name: REACT_APP_AMSA_LOGOUT_URL
              valueFrom:
                configMapKeyRef:
                  name: variables-env
                  key: AMSA_LOGOUT_URL
                  optional: true
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          imagePullPolicy: Always
