import { 
  faEye,
  faEyeSlash,
  faBell,
} from '@fortawesome/free-regular-svg-icons'
import {
  faCircleHalfStroke,
  faRightFromBracket,
  faGear,
  faInfo,
  faHouse,
  faCircleUser,
  faMagnifyingGlass,
  faArrowTurnDown,
  faSliders,
  faDownload,
  faPlus,
  faArrowDown,
  faCircleInfo,
  faEnvelope,
  faAddressCard,
  faSquarePhone,
  faArrowRightToBracket,
  faBorderAll,
  faCircleCheck,
  faCircleXmark,
  faSquarePlus,
  faSquarePen,
  faTrashCan,
  faBan,
  faUsers,
  faEllipsis,
  faBoxArchive,
  faCircle,
  faClock,
  faCalendar,
  faCalendarXmark,
  faStar
} from '@fortawesome/free-solid-svg-icons'

export const icons = {
  bell: faBell,
  circleHalfStroke: faCircleHalfStroke,
  rightFromBracket: faRightFromBracket,
  gear: faGear,
  eye: faEye,
  eyeSlash: faEyeSlash,
  info: faInfo,
  house: faHouse,
  circleUser: faCircleUser,
  magnifyingGlass: faMagnifyingGlass,
  arrowTurnDown: faArrowTurnDown,
  sliders: faSliders,
  download: faDownload,
  plus: faPlus,
  arrowDown: faArrowDown,
  circleInfo: faCircleInfo,
  envelope: faEnvelope,
  addressCard: faAddressCard,
  squarePhone: faSquarePhone,
  arrowRightToBracket: faArrowRightToBracket,
  borderAll: faBorderAll,
  circleCheck: faCircleCheck,
  circleXmark: faCircleXmark,
  squarePlus: faSquarePlus,
  squarePen: faSquarePen,
  trashCan: faTrashCan,
  ban: faBan,
  users: faUsers,
  ellipsis: faEllipsis,
  boxArchive: faBoxArchive,
  circle: faCircle,
  clock: faClock,
  calendar: faCalendar,
  calendarXmark: faCalendarXmark,
  star: faStar
}